# Generated by Django 4.1 on 2026-03-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('km', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalles', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='autos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('analisis_ia', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='autos.auto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('titulo', 'Título del Vehículo'), ('libre_deuda', 'Libre de Deuda'), ('vtv', 'VTV'), ('seguro', 'Seguro'), ('otro', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='autos.auto')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_instagram', models.TextField(blank=True)),
                ('copy_facebook', models.TextField(blank=True)),
                ('texto_mercadolibre', models.TextField(blank=True)),
                ('consejos', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='autos.auto')),
            ],
        ),
    ]
