# Generated by Django 4.1 on 2026-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidogenerado',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
