# Generated by Django 4.1 on 2026-03-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_contenidogenerado_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='GastoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fijo', 'A cargo de Todo @l Día'), ('variable', 'Gasto adicional')], default='variable', max_length=20)),
                ('categoria_fija', models.CharField(blank=True, choices=[('limpieza', 'Limpieza del vehículo'), ('publicacion', 'Publicación de fotos'), ('cochera', 'Cochera / guardado'), ('fotos_profesionales', 'Fotos y videos / reels profesionales'), ('otro_fijo', 'Otro servicio incluido')], max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='autos.auto')),
            ],
        ),
    ]
