# Generated by Django 4.1 on 2026-03-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_precio_compra_gastoauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=200)),
                ('telefono_cliente', models.CharField(blank=True, max_length=50)),
                ('tiene_titulo', models.BooleanField(default=False)),
                ('tiene_dni_titular', models.BooleanField(default=False)),
                ('tiene_vtv', models.BooleanField(default=False)),
                ('tiene_seguro', models.BooleanField(default=False)),
                ('tiene_libre_deuda', models.BooleanField(default=False)),
                ('tiene_service_history', models.BooleanField(default=False)),
                ('tiene_llave_duplicado', models.BooleanField(default=False)),
                ('tiene_manual', models.BooleanField(default=False)),
                ('estado_carroceria', models.CharField(choices=[('impecable', 'Impecable'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('con_detalles', 'Con detalles')], default='bueno', max_length=20)),
                ('detalles_carroceria', models.TextField(blank=True)),
                ('tiene_gato', models.BooleanField(default=False)),
                ('tiene_rueda_auxilio', models.BooleanField(default=False)),
                ('tiene_balizas', models.BooleanField(default=False)),
                ('kilometraje_ingreso', models.IntegerField(blank=True, null=True)),
                ('combustible_ingreso', models.CharField(choices=[('lleno', 'Lleno'), ('tres_cuartos', '3/4'), ('medio', '1/2'), ('cuarto', '1/4'), ('reserva', 'Reserva')], default='medio', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('firma_cliente', models.BooleanField(default=False)),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='autos.auto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='recepciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='autos.recepcionauto')),
            ],
        ),
    ]
