# Generated by Django 4.1 on 2026-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_recepcionauto_documentorecepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gastoauto',
            name='categoria_fija',
            field=models.CharField(blank=True, choices=[('limpieza', 'Limpieza del vehículo'), ('publicacion', 'Publicación de fotos'), ('cochera', 'Cochera / guardado'), ('fotos_profesionales', 'Fotos y videos / reels profesionales'), ('otro_fijo', 'Otro servicio incluido'), ('gestoria', 'Gestoría y tramitación de papeles sin vueltas')], max_length=30),
        ),
    ]
