# Generated by Django 4.1 on 2026-03-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_auto_moneda_auto_tipo_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='detalles_adicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='telefono_dueno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('lead', 'Lead')], default='disponible', max_length=20),
        ),
    ]
