# Generated by Django 4.1 on 2026-03-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_auto_detalles_adicionales_auto_telefono_dueno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoauto',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='tiene_08_firmado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='tiene_grabado_autopartes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='tiene_verificacion_policial',
            field=models.BooleanField(default=True),
        ),
    ]
