# Generated by Django 4.1 on 2026-03-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_gastoauto_comprobante_recepcionauto_tiene_08_firmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidogenerado',
            name='copy_informe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidogenerado',
            name='copy_recepcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gastoauto',
            name='bonificado',
            field=models.BooleanField(default=False),
        ),
    ]
