# Generated by Django 4.1 on 2026-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0008_contenidogenerado_copy_informe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoauto',
            name='bonificado',
            field=models.BooleanField(default=True),
        ),
    ]
