# Generated by Django 4.1 on 2026-03-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0009_alter_gastoauto_bonificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionauto',
            name='firma_cliente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_balizas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_dni_titular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_gato',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_libre_deuda',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_llave_duplicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_manual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_rueda_auxilio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_seguro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_service_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_titulo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recepcionauto',
            name='tiene_vtv',
            field=models.BooleanField(default=True),
        ),
    ]
