# Generated by Django 4.1 on 2026-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0010_alter_recepcionauto_firma_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionauto',
            name='funciona_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='funciona_calefaccion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='funciona_cierre_central',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='funciona_luces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcionauto',
            name='funciona_vidrios',
            field=models.BooleanField(default=True),
        ),
    ]
