# Generated by Django 4.1 on 2026-03-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0011_recepcionauto_funciona_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='nombre_dueno',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
