# Generated by Django 4.1 on 2026-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0012_auto_nombre_dueno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nombre_cliente', models.CharField(blank=True, max_length=200)),
                ('telefono_cliente', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
