# Generated by Django 4.1 on 2026-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0013_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
