# Generated by Django 4.1 on 2026-03-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0014_pedido_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='lead_estado',
            field=models.CharField(blank=True, choices=[('sin_contacto', 'Sin contacto'), ('contactado', 'Contactado sin visita'), ('visitado', 'Visitado — cerrando')], default='sin_contacto', max_length=20),
        ),
        migrations.AddField(
            model_name='auto',
            name='lead_origen',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('web', 'Web'), ('meta_ads', 'Meta Ads')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='auto',
            name='lead_precio_pedido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='lead_temperatura',
            field=models.CharField(blank=True, choices=[('caliente', 'Caliente'), ('tibio', 'Tibio'), ('frio', 'Frío')], default='tibio', max_length=10),
        ),
        migrations.CreateModel(
            name='LeadRechazado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('precio', 'Precio'), ('documentacion', 'Documentación'), ('danos', 'Daños'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('origen_lead', models.CharField(blank=True, max_length=20)),
                ('dias_en_pipeline', models.IntegerField(default=0)),
                ('columna_rechazo', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso_lead', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_rechazo', to='autos.auto')),
            ],
        ),
        migrations.CreateModel(
            name='LeadComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentario manual'), ('cambio_estado', 'Cambio de estado'), ('temperatura', 'Cambio de temperatura')], default='comentario', max_length=20)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comentarios', to='autos.auto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
