# Generated by Django 4.1 on 2026-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0015_auto_lead_estado_auto_lead_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidogenerado',
            name='copy_whatsapp',
            field=models.TextField(blank=True),
        ),
    ]
