# Generated by Django 4.1 on 2026-04-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0016_contenidogenerado_copy_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alcance', models.IntegerField(default=0, help_text='Personas alcanzadas')),
                ('impresiones', models.IntegerField(default=0)),
                ('interacciones', models.IntegerField(default=0)),
                ('seguidores_nuevos', models.IntegerField(default=0)),
                ('mejor_post', models.CharField(blank=True, help_text='Descripción del post que más funcionó', max_length=200)),
                ('consultas_recibidas', models.IntegerField(default=0, help_text='Consultas por WhatsApp/Instagram')),
                ('visitas_al_local', models.IntegerField(default=0)),
                ('publicaciones_realizadas', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
