# Generated by Django 5.2.12 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0017_metricassemanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos $'), ('USD', 'Dólares USD')], default='ARS', max_length=3),
        ),
    ]
