from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('app/', views.index_app, name='index_app'),    
    path('auto/nuevo/', views.nuevo_auto, name='nuevo_auto'),
    path('auto/<int:auto_id>/', views.detalle_auto, name='detalle_auto'),
    path('auto/<int:auto_id>/editar/', views.editar_auto, name='editar_auto'),
    path('auto/<int:auto_id>/borrar/', views.borrar_auto, name='borrar_auto'),
    path('auto/<int:auto_id>/analizar/', views.analizar_fotos, name='analizar_fotos'),
    path('auto/<int:auto_id>/contenido/', views.generar_contenido, name='generar_contenido'),
    path('auto/<int:auto_id>/estado/', views.cambiar_estado, name='cambiar_estado'),
    path('auto/<int:auto_id>/pack/', views.generar_pack, name='generar_pack'),
    path('auto/<int:auto_id>/pack/ver/', views.ver_pack, name='ver_pack'),
    path('auto/<int:auto_id>/vendido/ver/', views.ver_vendido, name='ver_vendido'),
    path('foto/<int:foto_id>/aprobar/', views.aprobar_foto, name='aprobar_foto'),
    path('foto/<int:foto_id>/borrar/', views.borrar_foto, name='borrar_foto'),
    path('auto/<int:auto_id>/gastos/', views.gastos_auto, name='gastos_auto'),
    path('auto/<int:auto_id>/gastos/borrar/<int:gasto_id>/', views.borrar_gasto, name='borrar_gasto'),
    path('auto/<int:auto_id>/recepcion/', views.recepcion_auto, name='recepcion_auto'),
    path('auto/<int:auto_id>/recepcion/guardar/', views.guardar_recepcion, name='guardar_recepcion'),
    path('auto/<int:auto_id>/informe/', views.ver_informe, name='ver_informe'),
    path('auto/<int:auto_id>/comprobante/', views.ver_comprobante, name='ver_comprobante'),
    path('auto/<int:auto_id>/guardar-moneda/', views.guardar_moneda, name='guardar_moneda'),
    path('auto/<int:auto_id>/gastos/editar/<int:gasto_id>/', views.editar_gasto, name='editar_gasto'),
    path('auto/<int:auto_id>/guardar-precio/', views.guardar_precio, name='guardar_precio'),
    path('auto/<int:auto_id>/json/', views.auto_json),
    path('auto/<int:auto_id>/actualizar-datos/', views.actualizar_datos),
    path('auto/<int:auto_id>/regenerar-copy/', views.regenerar_copy),
    path('auto/<int:auto_id>/recepcion/guardar-json/', views.guardar_recepcion_json),
    path('recepcion/documento/<int:doc_id>/borrar/', views.borrar_documento_recepcion),
    path('auto/<int:auto_id>/gastos/crear/', views.crear_gasto),
    path('gasto/<int:gasto_id>/editar/', views.editar_gasto_inline),
    path('gasto/<int:gasto_id>/borrar-inline/', views.borrar_gasto_inline),
    path('auto/<int:auto_id>/generar-copy-informe/', views.generar_copy_informe),
    path('auto/<int:auto_id>/generar-copy-recepcion/', views.generar_copy_recepcion),
    path('pedidos/', views.pedidos),
    path('pedido/<int:pedido_id>/resolver/', views.resolver_pedido),
    path('pedido/<int:pedido_id>/borrar/', views.borrar_pedido),
    path('pedido/<int:pedido_id>/editar/', views.editar_pedido),
    path('leads/kanban/',                    views.leads_kanban),
    path('lead/<int:auto_id>/mover/',        views.lead_mover),
    path('lead/<int:auto_id>/comentario/',   views.lead_comentario_agregar),
    path('lead/<int:auto_id>/temperatura/',  views.lead_temperatura_cambiar),
    path('lead/<int:auto_id>/tomar/',        views.lead_tomar),
    path('lead/<int:auto_id>/rechazar/',     views.lead_rechazar),
    path('lead/<int:auto_id>/historial/',    views.lead_historial),
    path('auto/<int:auto_id>/agregar-fotos/', views.agregar_fotos, name='agregar_fotos'),
    path('cm/contexto/', views.community_manager_contexto),
    path('cm/chat/', views.community_manager_chat),
    path('cm/metricas/', views.metricas_semanales),
    path('publico/', views.publico, name='publico'),
    path('publico/consulta/', views.publico_consulta),
    path('publico/consignacion/', views.publico_consignacion),
    path('publico/pedido/', views.publico_pedido),
    path('publico/stock/', views.publico_stock_json),
    path('publico/fotos/<int:auto_id>/', views.publico_fotos),
  

]
